-- =============================================================================
-- SECURITY HARDENING — CareComply Production
-- 2026-05-27
--
-- 1. Revoke all anon grants on sensitive tables
-- 2. Add get_my_org_ids() and is_platform_admin() STABLE helper functions
-- 3. Add performance indexes
-- 4. Add pgcrypto PII encryption infrastructure
-- 5. Add missing write RLS policies
--    - organizations (INSERT)
--    - profiles (UPDATE)
--    - document_types (INSERT, UPDATE, DELETE)
--    - documents (DELETE)
--    - reminders (INSERT, UPDATE, DELETE)
--    - organization_memberships (INSERT, UPDATE, DELETE)
--    - roles (INSERT, UPDATE, DELETE)
--    - role_permissions (INSERT, UPDATE, DELETE)
-- 6. Restrict permissions table to org members only
-- 7. Add auth_audit_events RLS insert policy + revoke anon
-- 8. Storage RLS policies for carer-documents and avatars buckets
-- 9. Audit log immutability trigger
-- =============================================================================

-- =============================================================================
-- PHASE 1: Revoke all anon table grants
-- =============================================================================

-- Core tenant tables — these were auto-generated by Supabase migrations and
-- should never be accessible to anonymous (unauthenticated) requests.
-- RLS would block actual access, but defence-in-depth: remove the grant too.

revoke all on table public.carers from anon;
revoke all on table public.document_types from anon;
revoke all on table public.documents from anon;
revoke all on table public.organization_memberships from anon;
revoke all on table public.organizations from anon;
revoke all on table public.permissions from anon;
revoke all on table public.profiles from anon;
revoke all on table public.role_permissions from anon;
revoke all on table public.roles from anon;
revoke all on table public.audit_logs from anon;
revoke all on table public.carer_references from anon;
revoke all on table public.organization_billing from anon;
revoke all on table public.organization_invitations from anon;
revoke all on table public.reminder_logs from anon;
revoke all on table public.reminders from anon;
revoke all on table public.stripe_events from anon;
revoke all on table public.auth_audit_events from anon;

-- =============================================================================
-- PHASE 2: Helper functions (STABLE + SECURITY DEFINER = cached per transaction)
-- =============================================================================

-- Returns all active organization IDs for the current user.
-- Used in RLS policies to replace repeated subqueries.
create or replace function public.get_my_org_ids()
returns uuid[]
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    array_agg(om.organization_id),
    '{}'::uuid[]
  )
  from public.organization_memberships om
  where om.user_id = auth.uid()
    and om.deleted_at is null
    and coalesce(om.status, 'active') in ('active', 'on_leave');
$$;

-- Returns true if the current user is a platform admin.
-- Equivalent to the middleware platform_memberships query.
create or replace function public.is_platform_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.platform_memberships
    where user_id = auth.uid()
  );
$$;

-- =============================================================================
-- PHASE 3: Performance indexes
-- =============================================================================

-- Speeds up the most common RLS patterns: membership lookups, org-scoped reads,
-- document expiry queries, and carer status filters.

create index if not exists idx_org_memberships_user_active
  on public.organization_memberships (user_id, organization_id)
  where deleted_at is null;

create index if not exists idx_carers_org_status
  on public.carers (organization_id, status);

create index if not exists idx_documents_carer_type_status
  on public.documents (carer_id, document_type_id, status)
  where superseded_by is null;

create index if not exists idx_documents_expiry
  on public.documents (expiry_date)
  where status = 'approved' and expiry_date is not null and superseded_by is null;

create index if not exists idx_reminders_org_active
  on public.reminders (organization_id)
  where is_active = true;

create index if not exists idx_audit_logs_org_created
  on public.audit_logs (organization_id, created_at desc);

create index if not exists idx_carer_references_carer
  on public.carer_references (carer_id, status);

create index if not exists idx_platform_memberships_user
  on public.platform_memberships (user_id);

-- =============================================================================
-- PHASE 4: PII encryption infrastructure
-- =============================================================================

-- Enable pgcrypto for AES-256 symmetric encryption.
-- Required for NI number, passport number, DBS certificate number fields.
create extension if not exists pgcrypto;

-- Encryption key: stored as a platform setting, NOT hardcoded here.
-- The functions below read from platform_settings at runtime. This avoids
-- baking secrets into the migration file itself.
-- Before deploying, insert the key:
--   insert into public.platform_settings (key, value)
--   values ('pii_encryption_key', '<strong-random-secret>')
--   on conflict (key) do nothing;

-- Encrypt a plaintext string. Returns NULL if input is NULL.
create or replace function public.pii_encrypt(p_plaintext text)
returns bytea
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_key text;
begin
  if p_plaintext is null then
    return null;
  end if;
  select value into v_key
  from public.platform_settings
  where key = 'pii_encryption_key';
  if v_key is null then
    raise exception 'pii_encryption_key not configured in platform_settings';
  end if;
  return extensions.pgp_sym_encrypt(p_plaintext, v_key);
end;
$$;

-- Decrypt a bytea ciphertext. Returns NULL if input is NULL.
create or replace function public.pii_decrypt(p_ciphertext bytea)
returns text
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_key text;
begin
  if p_ciphertext is null then
    return null;
  end if;
  select value into v_key
  from public.platform_settings
  where key = 'pii_encryption_key';
  if v_key is null then
    raise exception 'pii_encryption_key not configured in platform_settings';
  end if;
  return extensions.pgp_sym_decrypt(p_ciphertext, v_key);
end;
$$;

-- Add encrypted PII columns to carers (if not already present).
-- These store NI number, passport number, and DBS certificate number.
-- The plaintext equivalents can be removed once application code is migrated.
alter table public.carers
  add column if not exists national_insurance_encrypted bytea,
  add column if not exists passport_number_encrypted bytea,
  add column if not exists dbs_certificate_encrypted bytea;

-- =============================================================================
-- PHASE 5: Missing write RLS policies
-- =============================================================================

-- ─── organizations: INSERT ────────────────────────────────────────────────────
-- The create_organization_with_roles RPC runs as SECURITY DEFINER so it can
-- create orgs directly. However we add an INSERT policy for completeness in
-- case the function signature changes.
-- Only service_role or the RPC itself should ever insert rows here.
-- No policy needed for authenticated users — the RPC handles creation.

-- ─── profiles: UPDATE ─────────────────────────────────────────────────────────
drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
  on public.profiles
  for update
  to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

-- ─── document_types: INSERT / UPDATE / DELETE ──────────────────────────────
grant insert, update, delete on table public.document_types to authenticated;

drop policy if exists "Members can create document types" on public.document_types;
create policy "Members can create document types"
  on public.document_types
  for insert
  to authenticated
  with check (public.has_org_permission(organization_id, 'documents.edit'));

drop policy if exists "Members can update document types" on public.document_types;
create policy "Members can update document types"
  on public.document_types
  for update
  to authenticated
  using (public.has_org_permission(organization_id, 'documents.edit'))
  with check (public.has_org_permission(organization_id, 'documents.edit'));

drop policy if exists "Members can delete document types" on public.document_types;
create policy "Members can delete document types"
  on public.document_types
  for delete
  to authenticated
  using (public.has_org_permission(organization_id, 'documents.edit'));

-- ─── documents: DELETE ────────────────────────────────────────────────────────
drop policy if exists "Members can delete documents" on public.documents;
create policy "Members can delete documents"
  on public.documents
  for delete
  to authenticated
  using (
    public.has_org_permission(
      (select organization_id from public.carers where id = carer_id),
      'documents.edit'
    )
  );

-- ─── reminders: INSERT / UPDATE / DELETE ──────────────────────────────────────
drop policy if exists "Members can create reminders" on public.reminders;
create policy "Members can create reminders"
  on public.reminders
  for insert
  to authenticated
  with check (public.has_org_permission(organization_id, 'reminders.edit'));

drop policy if exists "Members can update reminders" on public.reminders;
create policy "Members can update reminders"
  on public.reminders
  for update
  to authenticated
  using (public.has_org_permission(organization_id, 'reminders.edit'))
  with check (public.has_org_permission(organization_id, 'reminders.edit'));

drop policy if exists "Members can delete reminders" on public.reminders;
create policy "Members can delete reminders"
  on public.reminders
  for delete
  to authenticated
  using (public.has_org_permission(organization_id, 'reminders.edit'));

-- ─── organization_memberships: INSERT / UPDATE / DELETE ───────────────────────
-- SELECT already covered by "Users can view own memberships" and
-- "Team viewers can view active organization memberships".
grant insert, update, delete on table public.organization_memberships to authenticated;

drop policy if exists "Admins can invite team members" on public.organization_memberships;
create policy "Admins can invite team members"
  on public.organization_memberships
  for insert
  to authenticated
  with check (public.has_org_permission(organization_id, 'team.invite'));

drop policy if exists "Admins can update team member roles" on public.organization_memberships;
create policy "Admins can update team member roles"
  on public.organization_memberships
  for update
  to authenticated
  using (public.has_org_permission(organization_id, 'team.manage'))
  with check (public.has_org_permission(organization_id, 'team.manage'));

drop policy if exists "Admins can remove team members" on public.organization_memberships;
create policy "Admins can remove team members"
  on public.organization_memberships
  for delete
  to authenticated
  using (
    -- Org admin removing someone else, or a user removing themselves
    public.has_org_permission(organization_id, 'team.manage')
    or user_id = auth.uid()
  );

-- ─── roles: INSERT / UPDATE / DELETE ─────────────────────────────────────────
-- SELECT already covered by "Members can view organization roles".
grant insert, update, delete on table public.roles to authenticated;

drop policy if exists "Admins can create org roles" on public.roles;
create policy "Admins can create org roles"
  on public.roles
  for insert
  to authenticated
  with check (
    organization_id is not null
    and public.has_org_permission(organization_id, 'roles.edit')
  );

drop policy if exists "Admins can update org roles" on public.roles;
create policy "Admins can update org roles"
  on public.roles
  for update
  to authenticated
  using (
    organization_id is not null
    and not is_system_role
    and public.has_org_permission(organization_id, 'roles.edit')
  )
  with check (
    organization_id is not null
    and not is_system_role
    and public.has_org_permission(organization_id, 'roles.edit')
  );

drop policy if exists "Admins can delete custom org roles" on public.roles;
create policy "Admins can delete custom org roles"
  on public.roles
  for delete
  to authenticated
  using (
    organization_id is not null
    and not is_system_role
    and public.has_org_permission(organization_id, 'roles.edit')
  );

-- ─── role_permissions: INSERT / UPDATE / DELETE ───────────────────────────────
-- SELECT already covered by "Members can view organization role permissions".
grant insert, update, delete on table public.role_permissions to authenticated;

drop policy if exists "Admins can assign role permissions" on public.role_permissions;
create policy "Admins can assign role permissions"
  on public.role_permissions
  for insert
  to authenticated
  with check (
    exists (
      select 1 from public.roles r
      where r.id = role_id
        and r.organization_id is not null
        and public.has_org_permission(r.organization_id, 'roles.edit')
    )
  );

drop policy if exists "Admins can remove role permissions" on public.role_permissions;
create policy "Admins can remove role permissions"
  on public.role_permissions
  for delete
  to authenticated
  using (
    exists (
      select 1 from public.roles r
      where r.id = role_id
        and r.organization_id is not null
        and public.has_org_permission(r.organization_id, 'roles.edit')
    )
  );

-- =============================================================================
-- PHASE 6: Restrict permissions table to org members only
-- =============================================================================

-- The previous policy allowed ALL authenticated users to enumerate every
-- permission code in the system. Replace it with a scoped read so users can
-- only see permissions relevant to at least one of their orgs' roles.
drop policy if exists "Authenticated users can view permissions" on public.permissions;
create policy "Org members can view relevant permissions"
  on public.permissions
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.role_permissions rp
      join public.roles r on r.id = rp.role_id
      where rp.permission_id = permissions.id
        and r.organization_id = any(public.get_my_org_ids())
    )
  );

-- =============================================================================
-- PHASE 7: auth_audit_events — revoke anon, add authenticated INSERT policy
-- =============================================================================

-- Unauthenticated users must never read or write auth audit events.
-- The anon revoke is already done in Phase 1 above.

-- Server-side actions (login, logout) run via the authenticated client and
-- need INSERT permission. SELECT remains blocked for non-service_role.
grant insert on table public.auth_audit_events to authenticated;

drop policy if exists "Authenticated users can insert auth audit events" on public.auth_audit_events;
create policy "Authenticated users can insert auth audit events"
  on public.auth_audit_events
  for insert
  to authenticated
  with check (true);

-- =============================================================================
-- PHASE 8: Storage RLS policies
-- =============================================================================

-- carer-documents bucket: files live at {organization_id}/{carer_id}/{filename}
-- org members with documents.view can read; documents.edit can write.

drop policy if exists "Org members can read carer documents" on storage.objects;
create policy "Org members can read carer documents"
  on storage.objects
  for select
  to authenticated
  using (
    bucket_id = 'carer-documents'
    and public.has_org_permission(
      (storage.foldername(name))[1]::uuid,
      'documents.view'
    )
  );

drop policy if exists "Org members can upload carer documents" on storage.objects;
create policy "Org members can upload carer documents"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'carer-documents'
    and public.has_org_permission(
      (storage.foldername(name))[1]::uuid,
      'documents.edit'
    )
  );

drop policy if exists "Org members can replace carer documents" on storage.objects;
create policy "Org members can replace carer documents"
  on storage.objects
  for update
  to authenticated
  using (
    bucket_id = 'carer-documents'
    and public.has_org_permission(
      (storage.foldername(name))[1]::uuid,
      'documents.edit'
    )
  );

drop policy if exists "Org members can delete carer documents" on storage.objects;
create policy "Org members can delete carer documents"
  on storage.objects
  for delete
  to authenticated
  using (
    bucket_id = 'carer-documents'
    and public.has_org_permission(
      (storage.foldername(name))[1]::uuid,
      'documents.edit'
    )
  );

-- avatars bucket: users can manage their own avatar only.
-- Create the bucket if it doesn't exist yet.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'avatars',
  'avatars',
  false,
  2097152, -- 2 MB
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do nothing;

drop policy if exists "Users can read own avatar" on storage.objects;
create policy "Users can read own avatar"
  on storage.objects
  for select
  to authenticated
  using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "Users can upload own avatar" on storage.objects;
create policy "Users can upload own avatar"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "Users can replace own avatar" on storage.objects;
create policy "Users can replace own avatar"
  on storage.objects
  for update
  to authenticated
  using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "Users can delete own avatar" on storage.objects;
create policy "Users can delete own avatar"
  on storage.objects
  for delete
  to authenticated
  using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- =============================================================================
-- PHASE 9: Audit log immutability trigger
-- =============================================================================

-- Prevent any UPDATE or DELETE on audit_logs. Only INSERTs are allowed.
-- service_role bypasses RLS but NOT triggers, so this is a hard backstop.

create or replace function public.prevent_audit_log_modification()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  raise exception 'Audit log records are immutable and cannot be modified or deleted.';
end;
$$;

drop trigger if exists audit_logs_immutable on public.audit_logs;
create trigger audit_logs_immutable
  before update or delete on public.audit_logs
  for each row execute function public.prevent_audit_log_modification();

-- Also apply to auth_audit_events
drop trigger if exists auth_audit_events_immutable on public.auth_audit_events;
create trigger auth_audit_events_immutable
  before update or delete on public.auth_audit_events
  for each row execute function public.prevent_audit_log_modification();

-- =============================================================================
-- Reload PostgREST schema cache
-- =============================================================================

notify pgrst, 'reload schema';
